#!/bin/bash
# dkclean
# description: Remove non-running Docker containers

set -e

# Only run as root
if [ $UID -ne 0 ]; then
  exec sudo $0
fi

# Grab the ID of exited containers and pass to docker rm
# We pass -v to rm to remove volumes, this might cause problems
docker ps -a | fgrep ' Exited ' | cut -d' ' -f 1 | xargs -r docker rm -v

# vi:ft=sh:sw=2:
