#!/bin/bash
# dkclean: Remove non-running Docker containers

set -e

# Only run as root
if [ $UID -ne 0 ]; then
  exec sudo $0
fi

containers=$(docker ps -a | fgrep ' Exited ' | cut -d' ' -f 1)
if [ -n "$(echo $containers | tr -d ' \n')" ]; then
  docker rm $containers
fi

# vi:ft=sh:sw=2:
