#!/bin/bash
# dkpurge: Remove all Docker containers and images

set -e

# Only run as root
if [ $UID -ne 0 ]; then
  exec sudo $0
fi

echo "Killing any running containers..."
docker ps -q | xargs -r docker kill

echo "Deleting all containers..."
docker ps -qa | xargs -r docker rm

echo "Deleting all images..."
function next_image() {
  image="$(docker images -qa | head -n 1)"
}
next_image
while [ -n "$image" ]; do
  docker rmi "$image"
  next_image
done

echo "Done."

# vi:ft=sh:sw=2:
