#!/bin/bash
# dkpurge
# description: Remove all Docker containers and images

set -eo pipefail
[[ $TRACE ]] && set -x

echo "Killing any running containers..."
docker ps -q | xargs -r docker kill

echo "Deleting all containers..."
docker ps -qa | xargs -r docker rm

echo "Deleting all images..."
next_image() {
  local images="$(docker images -qa)"
  images=( ${images/\n/ /} )
  image=${images[0]}
}
next_image
while [ -n "$image" ]; do
  docker rmi "$image"
  next_image
done

echo "Done."

# vi:ft=sh:sw=2:
