#!/bin/bash
# dksh: Start an interactive shell on the specified Docker image

set -e

# Only run as root
if [ $UID -ne 0 ]; then
  exec sudo "$0" "$1"
fi

docker run -it --entrypoint='/bin/bash' "$1" -i

# vi:ft=sh:sw=2:
