#!/bin/bash
# pi-run
# description: Copy a binary to the raspberry pi, then launch it

PI_SSH_HOST="pi"
PI_BIN_DIR="/home/pi"

set -eo pipefail

if [ $# -lt 1 ]; then
  echo "Usage: $0 <binary> [arg-1 .. [arg-N]]" >&2
  exit 1
fi

binary="$1"
shift

scp "$binary" "$PI_SSH_HOST:$PI_BIN_DIR/"
ssh -t "$PI_SSH_HOST" "sudo" "$PI_BIN_DIR/$binary" $@
