#!/bin/bash
# update-all-the-things
# description: git pull all my standard repos

# Repositories to pull, relative to $HOME
REPOS=(bin .vim .dotfiles .oh-my-zsh)
WARNCLR="\E[31m"
RESET="\E[0m"

function is_cwd_clean() {
  [ -z "$(git status --porcelain)" ]
}

for repo in "${REPOS[@]}"; do
  repodir="$HOME/$repo"
  if [ -d "$repodir" ]; then
    cd "$repodir"
    if is_cwd_clean; then
      echo -e "\nPulling $repodir:"
      git pull
    else
      echo -e "\n${WARNCLR}Skipping $repodir, it's dirty!$RESET"
    fi
  else
    echo -e "\nSkipping $repodir, it doesn't exist!"
  fi
done
